# Generated by Django 5.0.6 on 2024-07-02 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_pointing_date_code_company_pointing_date_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='wifis',
        ),
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=50)),
                ('bssid', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wifis', to='api.company')),
            ],
        ),
    ]
