# Generated by Django 5.0.6 on 2024-07-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_company_wifis_wifi'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
