# Generated by Django 5.0.6 on 2024-07-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_code_color_code_meaning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='color',
            field=models.CharField(blank=True, default='#95a5a6', max_length=20, null=True),
        ),
    ]
