# Generated by Django 5.0.6 on 2024-07-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_company_latitude_remove_company_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
