# Generated by Django 5.0.6 on 2024-07-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_employe_current_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='fonction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
