# Generated by Django 5.0.6 on 2024-07-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_fonction_employe_function_employe_can_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='can_login',
            new_name='is_first_login',
        ),
    ]
