services:
  backend:
    build:
      context: ./backend
    command: gunicorn codeITPointage.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8009:8000"
    volumes:
      - ./backend:/backend
    
    env_file:
      - ./backend/.env 

  frontend:
    build:
      context: ./dashboard
    volumes:
      - frontend_build:/dashboard/dist
    ports:
      - "3009:3000"


volumes:
  frontend_build:
