services:
  backend:
    build:
      context: ./backend
    command: gunicorn codeITPointage.wsgi:application --bind 0.0.0.0:8009
    ports:
      - "8009:8009"
    volumes:
      - ./backend:/backend
    
    env_file:
      - ./backend/.env  # If you have any environment variables

  frontend:
    build:
      context: ./dashboard
    volumes:
      - frontend_build:/dashboard/dist
    ports:
      - "3009:3009"


volumes:
  frontend_build:
