# Generated by Django 5.0.6 on 2024-07-02 09:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_active_alter_profile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointing',
            name='date',
        ),
        migrations.AddField(
            model_name='code',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='api.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointing',
            name='date_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pointing',
            name='date_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointing',
            name='pause_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointing',
            name='pause_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
