# Generated by Django 5.0.6 on 2024-07-02 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_company_latitude_company_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointing',
            old_name='date_out',
            new_name='break_end_time',
        ),
        migrations.RenameField(
            model_name='pointing',
            old_name='pause_in',
            new_name='break_start_time',
        ),
        migrations.RenameField(
            model_name='pointing',
            old_name='date_in',
            new_name='clock_in_time',
        ),
        migrations.RenameField(
            model_name='pointing',
            old_name='pause_out',
            new_name='clock_out_time',
        ),
        migrations.AddField(
            model_name='pointing',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
