# Generated by Django 5.0.6 on 2024-07-02 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_pointing_status_alter_pointing_clock_in_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointing',
            name='clock_in_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 13, 27, 56, 908279, tzinfo=datetime.timezone.utc)),
        ),
    ]
