# Generated by Django 5.0.6 on 2024-07-02 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_pointing_clock_in_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointing',
            name='clock_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
