# Generated by Django 5.0.6 on 2024-07-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_pointing_clock_in_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointing',
            name='status',
            field=models.CharField(blank=True, choices=[('W', 'WORKING'), ('B', 'BREAK'), ('WAB', 'WORKING_AFTER_BREAK'), ('D', 'DONE')], max_length=20, null=True),
        ),
    ]
