# Generated by Django 5.0.6 on 2024-07-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_code_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='role',
            field=models.CharField(blank=True, choices=[('D', 'DONE'), ('W', 'WORKING'), ('B', 'BREAK'), ('A', 'ABSENT')], max_length=20, null=True),
        ),
    ]
