# Generated by Django 5.0.6 on 2024-07-13 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='company',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='pointing',
            name='break_end_time',
        ),
        migrations.RemoveField(
            model_name='pointing',
            name='break_start_time',
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('pointing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='api.pointing')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='api.company')),
            ],
        ),
    ]
