# Generated by Django 5.0.6 on 2024-07-13 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_break_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='current_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='api.station'),
        ),
    ]
