# Generated by Django 5.0.6 on 2024-07-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_employe_fonction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='fonction',
            new_name='function',
        ),
        migrations.AddField(
            model_name='employe',
            name='can_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='mac_address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
